### ISSUE TITLE
Cannot be downloaded might inappropriate content

### ISSUE THREAD

**Issue by Turhvjbufv** [zWolfrost/spotify-dlp#2]
Sorry to bother you again. 
The problem is when this happens it stop all the downloads 
Example: has 4 songs to download 
2 song needs to be logged in so download isn't working and yt-dlp is throwing "sign in to confirm your age...", so now it just stops, if you could make it just skip over that song and continue over the other songs

**Comment by zWolfrost** [comment]
No problem, I'm really sorry that you are having problems with the script
Are you using version v2.1.0 or v2.1.1? (just do `spotify-dlp --version` to know) I might have changed something that caused that.
Regardless, could you provide me with the name of the song that is causing this, either here or by e-mail if you don't feel comfortable to? (So that i can debug this issue faster)
